import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/* jsPDF's default helvetica is WinAnsi (CP1252) — characters outside that
   set (e.g. the rupee sign ₹ U+20B9, en/em dashes, smart quotes) render as
   garbled glyphs with broken kerning. Map them to safe ASCII equivalents. */
const sanitize = (input) => {
  if (input === null || input === undefined) return "";
  return String(input)
    .replace(/₹/g, "Rs.")
    .replace(/[–—]/g, "-")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'");
};

const generateCalculatorPDF = ({
  title,
  subtitle,
  inputs = {},
  outputs = {},
  formula,
  highlight,
  notes,
}) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  /* ================================
     COLORS
  ================================= */

  const ACCENT = [255, 107, 26];
  const ACCENT_DARK = [200, 78, 10];
  const TEXT = [25, 25, 25];
  const MUTED = [95, 95, 95];
  const SUBTEXT = [130, 130, 130];
  const BORDER = [225, 225, 225];
  const SOFT = [248, 249, 250];
  const ACCENT_SOFT = [255, 244, 236];
  const HIGHLIGHT = [255, 251, 247];

  /* ================================
     PAGE
  ================================= */

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const marginX = 18;
  const contentWidth = pageWidth - marginX * 2;

  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  /* ================================
     HEADER
  ================================= */

  doc.setFillColor(...ACCENT);
  doc.rect(0, 0, pageWidth, 4, "F");

  let y = 14;

  try {
    doc.addImage("/dark-logo.png", "PNG", marginX, y, 18, 18);
  } catch (error) {
    /* logo optional */
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...TEXT);
  doc.text("Bhavyam Steel", marginX + 22, y + 7);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...SUBTEXT);
  doc.text("Smart Steel Calculation Report", marginX + 22, y + 12);

  const badgeX = pageWidth - marginX - 42;
  doc.setFillColor(...ACCENT_SOFT);
  doc.roundedRect(badgeX, y, 42, 10, 5, 5, "F");
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...ACCENT);
  doc.text("CALCULATION REPORT", badgeX + 21, y + 6.3, { align: "center" });

  y = 38;
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.3);
  doc.line(marginX, y, pageWidth - marginX, y);

  /* ================================
     TITLE + META
  ================================= */

  y += 9;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.setTextColor(...TEXT);
  doc.text(sanitize(title), marginX, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...MUTED);
  doc.text(
    sanitize(subtitle || "Generated by Bhavyam Steel Smart Tools"),
    marginX,
    y + 5,
  );

  doc.setDrawColor(...ACCENT);
  doc.setLineWidth(0.8);
  doc.line(marginX, y + 2, marginX + 30, y + 2);

  /* Meta Box */
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
  const refNo = `BS-${now.getFullYear()}${(now.getMonth() + 1)
    .toString()
    .padStart(2, "0")}${now.getDate().toString().padStart(2, "0")}-${Math.floor(
    Math.random() * 9000 + 1000,
  )}`;

  const metaX = pageWidth - marginX - 60;
  const metaY = y - 4;
  doc.setFillColor(...SOFT);
  doc.setDrawColor(...BORDER);
  doc.roundedRect(metaX, metaY, 60, 16, 2, 2, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...SUBTEXT);
  doc.text("REPORT DATE", metaX + 3, metaY + 4);
  doc.text("REFERENCE NO.", metaX + 3, metaY + 11);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...TEXT);
  doc.text(dateStr, metaX + 28, metaY + 4);
  doc.text(refNo, metaX + 28, metaY + 11);

  y += 16;

  /* ================================
     SECTION HELPERS
  ================================= */

  const drawSectionHeading = (text) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...ACCENT);
    doc.text(text, marginX, y);

    doc.setDrawColor(...ACCENT);
    doc.setLineWidth(0.4);
    doc.line(marginX, y + 1.5, marginX + 50, y + 1.5);

    y += 4;
  };

  const baseTableStyles = {
    font: "helvetica",
    fontSize: 9,
    cellPadding: { top: 2.2, bottom: 2.2, left: 3, right: 3 },
    textColor: TEXT,
    lineColor: BORDER,
    lineWidth: 0.2,
    valign: "middle",
    overflow: "linebreak",
  };

  /* ================================
     INPUT TABLE
  ================================= */

  const inputEntries = Object.entries(inputs).filter(
    ([, v]) => v !== undefined && v !== null && v !== "",
  );

  if (inputEntries.length > 0) {
    drawSectionHeading("INPUT SPECIFICATIONS");

    autoTable(doc, {
      startY: y,
      head: [["#", "Specification", "Value"]],
      body: inputEntries.map(([k, v], i) => [
        (i + 1).toString().padStart(2, "0"),
        sanitize(k),
        sanitize(v),
      ]),
      theme: "grid",
      styles: baseTableStyles,
      headStyles: {
        fillColor: TEXT,
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 8.5,
        cellPadding: { top: 2.5, bottom: 2.5, left: 3, right: 3 },
      },
      bodyStyles: { fillColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: SOFT },
      columnStyles: {
        0: {
          cellWidth: 12,
          halign: "center",
          textColor: SUBTEXT,
          fontStyle: "bold",
        },
        1: { cellWidth: 70, fontStyle: "bold" },
        2: { halign: "right" },
      },
      margin: { left: marginX, right: marginX },
      tableWidth: contentWidth,
    });

    y = doc.lastAutoTable.finalY + 9;
  }

  /* ================================
     OUTPUT TABLE
  ================================= */

  const outputEntries = Object.entries(outputs).filter(
    ([, v]) => v !== undefined && v !== null && v !== "",
  );

  if (outputEntries.length > 0) {
    drawSectionHeading("CALCULATION RESULTS");

    autoTable(doc, {
      startY: y,
      head: [["#", "Result", "Value"]],
      body: outputEntries.map(([k, v], i) => [
        (i + 1).toString().padStart(2, "0"),
        sanitize(k),
        sanitize(v),
      ]),
      theme: "grid",
      styles: baseTableStyles,
      headStyles: {
        fillColor: ACCENT,
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 8.5,
        cellPadding: { top: 2.5, bottom: 2.5, left: 3, right: 3 },
      },
      bodyStyles: { fillColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: HIGHLIGHT },
      columnStyles: {
        0: {
          cellWidth: 12,
          halign: "center",
          textColor: SUBTEXT,
          fontStyle: "bold",
        },
        1: { cellWidth: 70, fontStyle: "bold" },
        2: { halign: "right", textColor: ACCENT_DARK, fontStyle: "bold" },
      },
      margin: { left: marginX, right: marginX },
      tableWidth: contentWidth,
    });

    y = doc.lastAutoTable.finalY + 8;
  }

  /* ================================
     HIGHLIGHT BANNER (dynamic, only if provided)
  ================================= */

  if (highlight && highlight.value !== undefined && highlight.value !== null) {
    const label = sanitize(highlight.label || "RESULT").toUpperCase();
    const valueStr = sanitize(highlight.value);
    const note = highlight.note ? sanitize(highlight.note) : "";

    /* Measure value text at preferred 14pt; if it doesn't fit inline, stack it. */
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    const valueWidth = doc.getTextWidth(valueStr);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    const labelWidth = doc.getTextWidth(label);

    const inlineSpace = contentWidth - labelWidth - 16;

    if (valueWidth <= inlineSpace) {
      /* Inline layout: label left, value right */
      const bannerHeight = 14;
      doc.setFillColor(...ACCENT);
      doc.roundedRect(marginX, y, contentWidth, bannerHeight, 2, 2, "F");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(255, 255, 255);
      doc.text(label, marginX + 4, y + 5.5);

      if (note) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        doc.text(note, marginX + 4, y + 10.5);
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text(valueStr, pageWidth - marginX - 4, y + 9, { align: "right" });

      y += bannerHeight + 6;
    } else {
      /* Stacked layout: label on top, value wrapped below at smaller font */
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      const wrappedValue = doc.splitTextToSize(valueStr, contentWidth - 8);

      const headerBlock = 7;
      const noteBlock = note ? 4.5 : 0;
      const valueBlock = wrappedValue.length * 5.2 + 2;
      const bannerHeight = headerBlock + valueBlock + noteBlock + 3;

      doc.setFillColor(...ACCENT);
      doc.roundedRect(marginX, y, contentWidth, bannerHeight, 2, 2, "F");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(255, 255, 255);
      doc.text(label, marginX + 4, y + 5.5);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      let lineY = y + headerBlock + 5;
      wrappedValue.forEach((line) => {
        doc.text(line, marginX + 4, lineY);
        lineY += 5.2;
      });

      if (note) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        doc.text(note, marginX + 4, y + bannerHeight - 3);
      }

      y += bannerHeight + 6;
    }
  }

  /* ================================
     FORMULA REFERENCE (only if provided)
  ================================= */

  if (formula && (formula.expression || formula.label)) {
    const fLabel = sanitize(
      formula.label || "FORMULA REFERENCE",
    ).toUpperCase();
    const fExpr = sanitize(formula.expression || "");
    const fNote = formula.note ? sanitize(formula.note) : "";

    /* Wrap expression if very long */
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    const exprLines = doc.splitTextToSize(fExpr, contentWidth - 50);

    const boxHeight = 10 + exprLines.length * 5;

    doc.setFillColor(...ACCENT_SOFT);
    doc.setDrawColor(...ACCENT);
    doc.setLineWidth(0.2);
    doc.roundedRect(marginX, y, contentWidth, boxHeight, 2, 2, "FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...ACCENT);
    doc.text(fLabel, marginX + 4, y + 5.5);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...TEXT);
    let exprY = y + 11;
    exprLines.forEach((line) => {
      doc.text(line, marginX + 4, exprY);
      exprY += 5;
    });

    if (fNote) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      doc.text(fNote, pageWidth - marginX - 4, y + boxHeight - 3.5, {
        align: "right",
      });
    }

    y += boxHeight + 6;
  }

  /* ================================
     NOTES
  ================================= */

  const defaultNote =
    "Note: These calculations are estimates based on standard industry formulas. Actual values may vary slightly due to manufacturing tolerances and material grade variations.";

  const noteText = sanitize(
    Array.isArray(notes) ? notes.join(" ") : notes || defaultNote,
  );

  doc.setFont("helvetica", "italic");
  doc.setFontSize(7.5);
  doc.setTextColor(...SUBTEXT);
  const noteLines = doc.splitTextToSize(noteText, contentWidth);
  doc.text(noteLines, marginX, y);

  /* ================================
     FOOTER
  ================================= */

  const footerY = pageHeight - 18;

  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.3);
  doc.line(marginX, footerY - 4, pageWidth - marginX, footerY - 4);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(...TEXT);
  doc.text("Bhavyam Steel", marginX, footerY);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...SUBTEXT);
  doc.text("Generated from Smart Calculator Tool", marginX, footerY + 4);

  doc.setFontSize(7);
  doc.text(
    "This is a system generated report and does not require a signature.",
    pageWidth / 2,
    footerY + 4,
    { align: "center" },
  );

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(...ACCENT);
  doc.text("Page 1 of 1", pageWidth - marginX, footerY, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setTextColor(...SUBTEXT);
  doc.text(dateStr, pageWidth - marginX, footerY + 4, { align: "right" });

  /* ================================
     SAVE
  ================================= */

  const fileName = String(title || "calculation-report")
    .toLowerCase()
    .replace(/\s+/g, "-");
  doc.save(`${fileName}-${refNo}.pdf`);
};

export default generateCalculatorPDF;
